### ISSUE TITLE
RHOCS 4.3 ISO Boot Parameters

### ISSUE THREAD

**Issue by ahmbas** [chuckersjp/coreos-iso-maker#3]
Hi,

The isolinux.cfg file does not change the boot params of the ISO's kernel. It seems like it's not honoring it and the default kernel params are shown.

However, I got it to work though by adding the "{{cmd_args}}" to the grub.cfg
Once the "cmd_args" were added to the grub.cfg I was able to see my static IP configuration and iginition_url and image_url in the boot params and everything was gravy.

It was working fine for 4.2. I will open a PR shortly.

**Comment by chuckersjp** [comment]
I have had a review of your PR and learned a few things in the process.

From https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/anaconda_customization_guide/sect-boot-menu-customization

``` There are two different boot loaders on installation media. The ISOLINUX boot loader is used on systems with BIOS firmware, and the GRUB2 boot loader is used on systems with UEFI firmware. Both are present on all images for AMD64 and Intel 64 systems provided by Red Hat. ```

So, likely you are using UEFI booting rather than BIOS booting which might explain why you don't see it change. (Although I don't know why it would have worked for 4.2 and not for 4.3 but I believe the image did change to include both I think I recall hearing.)

It would probably be worth modifying BOTH `isolinux/isolinux.cfg` and `EFI/grub.cfg` but it will take a bit of thought on how to do it as the first `cmd_args` is rather different between the two.

Do you think you can modify your PR to change both files?  The `cmd_args` can probably be built the same and then just tweaked for the `isolinux.cfg` file just before it is modified.

The single version would require some a bit of hacking but should be doable as well.

**Comment by chuckersjp** [comment]
Crud.  Looking at this closer made me realise there is a bug that needs fixing.  The `append initrd=/images/initramfs.img nomodeset rd.neednet-1 coreos.inst=yes` ends up in there twice.

I am gonna fix that and add the bits from the `grub.cfg` as well on a new branch.

I am giving you full credit for finding this bug.

**Comment by chuckersjp** [comment]
Can you checkout the `uefi` branch and test it for me?  If it looks good, I will merge it in.

**Comment by chuckersjp** [comment]
Closing for now.
